[package]
name = "olive_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
phf = { version = "0.11.2", features = ["macros"] }

[dev-dependencies]
sdl2 = "0.37.0"
bytemuck = "1.18.0"

[features]
default = ["sdl"]
sdl = []
term = []
wasm = []
